[tool.poetry]
name = "Hdl21SchematicImporter"
version = "0.1.0"
description = ""
authors = ["Dan Fritchman <dan@fritch.mn>"]

[tool.poetry.dependencies]
python = "^3.10"
svgelements = "^1.7.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
